@Library('groovy-task') _
def mvn = '/opt/apache-maven-3.8.4/bin/mvn'

pipeline {
    agent { label 'mvn'}
    stages {
        stage('Checkout') {
            steps {
                script {
                    checkoutFrom('refs/tags/prometheus-2.0.10', 'https://github.com/jenkinsci/prometheus-plugin.git')
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    buildStep(mvn)
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    testStep(mvn)
                }
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '*/**.jar'
            archiveArtifacts artifacts: '*/**.hpi'
        }
    }
}
