pipeline {
    agent { label 'master'}

    stages {
        stage('Checkout') {
            steps {
                checkout scm: [$class: 'GitSCM', 
                userRemoteConfigs: [[url: 'https://github.com/jenkinsci/prometheus-plugin.git']],
                branches: [[name: 'refs/tags/prometheus-2.0.10']]],
                poll: false
            }
        }
        
        stage('Build') {
            steps {
                sh 'mvn clean install'
                sh 'mvn hpi:hpi'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }
    
    post {
        success {
            archiveArtifacts artifacts: '*/**.jar'
            archiveArtifacts artifacts: '*/**.hpi'
        }
    }
}

