@Library('groovy-task') _
pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                script {
                    checkoutFrom('master', 'https://github.com/berolog/scripts.git')
                }              /* env.ghprbSourceBranch */
            
            }
        }
        stage('Build') {
            steps {
                script {
                    buildStep()
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    testStep()
                }
            }
        }
    }
    post {
        always {
            writeFile file: 'artifact.txt', text: currentBuild.result
            archiveArtifacts artifacts: 'artifact.txt'
        }
        failure {
            archiveArtifacts artifacts: 'test_result.txt'
        }

    }

}
