pipeline {
    agent { label 'docker-slave-ssh' }
    stages {
            stage('Clone') {
            steps {
                git branch: 'dev', 
                credentialsId: 'ssh-key-vm2', 
                url: 'git@github.com:berolog/scripts.git'
            }
            }
    
            stage('Build') {
            steps {
                sh './build.sh'
            }
            }
            stage('Test') {
            steps {
                sh './test.sh > test_result.txt'
            }
            }
    }
    post {
        always {
            writeFile file: 'artifact.txt', text: currentBuild.result 
            archiveArtifacts artifacts: 'artifact.txt'
        }
        failure {
            archiveArtifacts artifacts: 'test_result.txt'
        }

    }

}
