@Library('groovy-task') _
def rnd = new Random()
def mvn = '/opt/apache-maven-3.8.4/bin/mvn'

pipeline {
    agent { label 'mvn'}

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkoutFrom('refs/tags/prometheus-2.0.10', 'https://github.com/jenkinsci/prometheus-plugin.git')
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    sleep Math.abs(rnd.nextInt() % (60 - 10)) + 10
                    sh(libraryResource('generator.sh'))
                    buildStep(mvn)              
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sleep Math.abs(rnd.nextInt() % (60 - 10)) + 10
                    sh(libraryResource('generator.sh'))
                    testStep(mvn)
                }
            }
        }
    }

    post {
        success {
            archiveArtifacts artifacts: '*/**.jar'
            archiveArtifacts artifacts: '*/**.hpi'

        }
    }
}
